### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by northkode** [yazinsai/srt-ai#1]
Seems open ai just returns an ERROR but error doen't have anything valuable in it.

**Comment by Nave8** [comment]
Same here
Error during translation: [Error: OpenAI API returned an error]

**Comment by ekkutlu** [comment]
Same issue help for Error during translation: [Error: OpenAI API returned an error]

**Comment by heensuk** [comment]
> Same issue help for Error during translation: [Error: OpenAI API returned an error]

I had the same issue, and it happened because the file (srt) was too lengthy

**Comment by bamkikovic** [comment]
Error during translation: [Error: OpenAI API returned an error]
