### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by romantci2710** [yazinsai/srt-ai#13]
I got this error with long text srt file. short and very short not happend.

![screenshot_1705287780](https://github.com/yazinsai/srt-ai/assets/63484625/b5369b96-899d-4c6e-9610-9ea421f57c9d)

**Comment by yazinsai** [comment]
Is it possible the SRT was malformed? Could you please share the file so I can try it out myself?

**Comment by romantci2710** [comment]
[W1 L2 S1-en - 11-20.zip](https://github.com/yazinsai/srt-ai/files/14001295/W1.L2.S1-en.-.11-20.zip)
Kindly check the file (zip)

**Comment by pdtan** [comment]
same here, how to fix
