### ISSUE TITLE
help me.

### ISSUE THREAD

**Issue by DjFluke99** [yazinsai/srt-ai#2]
#1 I'm having trouble understanding how to run the script on Windows. I've looked for online guides and YouTube videos, but I can't find anything. 

Can you help me? 

Thank you.

**Comment by KubaIA** [comment]
1. Clone the repo git clone https://github.com/yazinsai/srt-ai
2. Rename .env.example to .env.local and paste your OpenAI Key.
3. Install Node.JS
4. Run Node.Js command prompt, and Install dependencies using "npm run install"
5. Start locally using "npm run dev"
6. open in your browser:  http://localhost:3000/

**Comment by TakeshiCyRob** [comment]
> 1. Clone the repo git clone https://github.com/yazinsai/srt-ai
> 2. Rename .env.example to .env.local and paste your OpenAI Key.
> 3. Install Node.JS
> 4. Run Node.Js command prompt, and Install dependencies using "npm run install"
> 5. Start locally using "npm run dev"
> 6. open in your browser:  http://localhost:3000/

How do I rename the file? Do I have to do it in the command prompt? I didn't understand the steps...Where do I paste my OpenAI Key?

**Comment by alialowais** [comment]
You should show hidden files, but still there is issue and not working I don't why

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
