### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by bagadefente** [yazinsai/srt-ai#3]
Hi,
the project works really well, but I'd like to input a new language (pt-BR).

I tried a little using ChatGPT to guide me, but my coding knowledge is minimal... can anybody guide me at least from where to start?

thanks!

**Comment by ZijianLiang2000** [comment]
In directory srt-ai\components\Form.tsx, just add the new language you would like to translate into, within the array.

`const LANGUAGES = [
  "Arabic",
  "English",
  "French",
  "German",
  "Persian", 
  "Malay",
  "Spanish",
  "Turkish",
  "Chinese"
];`

This should be working, however the code is failing somewhere else for me, where the translated srt came out with only one line unfortunately.
