### ISSUE TITLE
Bounty award for a working version!

### ISSUE THREAD

**Issue by ibitzor** [yazinsai/srt-ai#5]
Hi,

Clearly, I'm not the only one NOT getting this script to work properly and the creator doesn't seem too frequently visit here.

I'm also getting the same error message as other reported users:

[Error: OpenAI API returned an error]

This would have been such a tremendous contribute the cinema world, across the globe, if it would work accordingly.

To the original creator; yazinsai or anyone else with the knowledge of how to get it to work accordingly.

I personally pledge you'll be compensated for your time to get a properly working script, with proper layman guidelines accompanying it. 

Considering the recent developments with OpenAI & ChatGPT, a requirement would be to not there being an input/output restriction of tokens/characters so you can input a regular movie SRT and it translating all in one go, if your account funds allow it.

For it to being able to detect any input language and you can select the specific output language would be the cherry on the top.

Hoping anyone else out there with the coding knowledge can see the global impact this script can have for cinema lovers across the globe, cheers!

**Comment by jppaolim** [comment]
yep, became crazy myself the other day trying to split a long file into subfiles manually, then modifying the code with the help of GPT ... ended up spending 3h .. .and finally discovered there is a free tool online, on the google translate basis which works perfectly and is free. Have a look :)

**Comment by yazinsai** [comment]
hey @ibitzor, sorry didn't notice this issue earlier. I'm digging into this to see why folks are reporting that it's not working.

**Comment by ibitzor** [comment]
Hi @yazinsai 

Appreciate it, but after all this time, I've now moved on to other working AI translation solutions.

Would still be good if you fixed your script as others seem to have had the same issue with it, cheers!

**Comment by yazinsai** [comment]
Thanks, curious which you ended up using?I'd love to compare output to some
others

**Comment by solova** [comment]
I got the same error and did some digging. The tool sends all subtitles together and gets an error "This model's maximum context length is 4097 tokens. However, your messages resulted in {SOMEBIGNUMBER} tokens."
It works well for small SRT files, but fails with real ones. 
The `gpt-3.5-turbo` model [has](https://platform.openai.com/docs/models/gpt-3-5) this small context window and possible solutions are to split subtitles into small parts (and lose context) or pay more for new OpenAI models with larger context windows.

**Comment by yazinsai** [comment]
Currently working on a new version that'll fix this!

**Comment by seghier** [comment]
the same error here
`Error during translation: [Error: OpenAI API returned an error]`
